### ISSUE TITLE
Create a Todo list?

### ISSUE THREAD

**Issue by adityaraute** [DiestroCorleone/tech-company-site-template#2]
## TODO LIST

- [x] Add proper links to the Facebook, Twitter, and Instagram profiles.
- [x] Create a favicon.
- [x] Scale images to match the text and other images.
- [x] Fix navbar hover issue.

**Comment by DiestroCorleone** [comment]
Solved the image size on the cards. The social media links are meant to be replaced with the ones from anyone who uses the template. And the other things... I'll work on them tomorrow. Thanks for your help!

**Comment by adityaraute** [comment]
Dunno if you intended it, but the Readme file is gone again.

**Comment by DiestroCorleone** [comment]
Fixed!

**Comment by DiestroCorleone** [comment]
Navbar hover issue fixed. Plus, I added a dropdown menu.

**Comment by DiestroCorleone** [comment]
Mission accomplished! Thanks for the tips, it certainly made me notice things I might have overlooked otherwise, and made me focus on details that (I'll be honest here) I would have probably ignored.
